apiVersion: v0.1
agent:
  image: some-image
stages:
  - name: A Broken Stage
    steps:
      - command: echo
        arguments: ["hello","world"]
    stages:
      - name: Nested
        steps:
          - command: echo
            arguments: ['oops']
