apiVersion: v0.1
agent:
  image: some-image
stages:
  - name: A Working Stage
    options:
      unstash:
        dir: some/dir
    steps:
      - command: echo
        args:
          - hello
          - world